### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by MaXGitteR** [gameblabla/retrostone2-buildroot#1] opened 2021-01-05 19:57 UTC
When trying to open terminal app, one only gets a black screen. After trying some times, it returns automatically to gmenu2x desktop.
cfw123

**Comment by gameblabla** [comment] 2021-01-06 14:57
The terminal app is mostly just here for debugging : it has no purpose other than that.
To exit out of the terminal, press start.
It works as intended so i'm closing this.

**Closed as completed by gameblabla** 2021-01-06 14:57 UTC
